#cloud-config

hostname: "${hostname}"
coreos:
  update:
    reboot-strategy: "best-effort"
  etcd2:
    name: "${hostname}"
    initial-cluster: "etcd-a=http://10.0.0.10:2380,etcd-c=http://10.0.64.10:2380,etcd-d=http://10.0.128.10:2380"
    advertise-client-urls: "http://$private_ipv4:2379"
    initial-advertise-peer-urls: "http://$private_ipv4:2380"
    listen-client-urls: "http://0.0.0.0:2379"
    listen-peer-urls: "http://$private_ipv4:2380"
  units:
    - name: "etcd2.service"
      command: "start"
